### ISSUE TITLE
Please Please share your knowledge to unlock bios...

### ISSUE THREAD

**Issue by profzei** [Zero-zer0/Matebook_13_14_2020_Hackintosh_OpenCore#4]
As in object, please could you share how to unlock bios CFG and DVMT related things?

I investigated your installation (thanks to Google translate...) in https://bbs.pcbeta.org/viewthread-1838014-1-110.html , but I can't access https://bbs.pcbeta.org/viewthread-1834965-1-2.html

I'd like to unlock my bios for Matebook X Pro 2018 edition
Cheers

**Comment by Zero-zer0** [comment]
Hello,

Sorry for delaying the guide I put into TODOs for so long.</br>
However, I don't want to write what I have done on my laptop due to settings in different laptops are varies. I only give some hints of tools needed to modify setup_vars in Insyde BIOS.</br>
But please remember, NO ONE will be responsible for any damage to your laptop in the process of BIOS unlocking.

However, I can give you some suggestions on unlocking DVMT and CFG Lock.
1. Backup your BIOS by `BIOS Backup TooKit`, or download the latest BIOS from the Huawei support website. Using 7-zip to extract `.exe` updater file and you will find the BIOS image with `.bin` file extension.

2. Use `UEFITools` to find `PE32 Image` related to the settings. Just search `CFG Lock` of `DVMT`, they perhaps lie in the same `PE32 Image` module.

3. Extract the `PE32 Image` module and analyze by `ifrextract`, then you will get a `.txt` file with most setup vars inside.

4. Search for `CFG Lock` and `DVMT` to find the settings you want to change. Takedown the settings you want to modify. </br> 

```
One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x3E, VarStore: 0x3, QuestionId: 0x16E, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 5C 03 5D 03 6E 01 03 00 3E 00 10 10 00 01 00}
 			One Of Option: Disabled, Value (8 bit): 0x0 {09 07 04 00 00 00 00}
 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 03 00 30 00 01}
		       End One Of {29 02}
```


  - For example, the information of `CFG Lock`  contains `VarStoreInfo (VarOffset/VarName): 0x3E `, which indicates to the place where it lies in the section of `CPUSetup` </br>
    - `VarStore 0x3`(Which indicates to the `CPUSetup` section, you can find them at the beginning of the .txt file)
```
VarStore: VarStoreId: 0x3 [B08F97FF-E6E8-4193-A997-5E9E9B0ADB32], Size: 0x23A, Name: CpuSetup {24 1F FF 97 8F B0 E8 E6 93 41 A9 97 5E 9E 9B 0A DB 32 03 00 3A 02 43 70 75 53 65 74 75 70 00}
```
</br>
    - The options are `01` and `00`, with CFG Lock Enabled or Disabled. </br>

- The trace to modify this setting is
 `CFG Lock`: CPUSetup--> Offset 0x3E --> change from `01` to `00`

5.  Make use of H2OUVE or RU.efi to do such settings. Modified grub with `setup_var` is not compatible with Insyde's BIOS. Here are some hints:
- as for RU.efi, just use `Alt`+`+/=` to find the sections you want like `CPUSetup` or `SaSetup`
- the HEX on the left upper corner shows the place of the Offset.
- Ctrl+W to write out.

Some resources could help:
- [Link1](https://www.misonsky.cn/115.html)
- [RU.efi](http://ruexe.blogspot.com/)
- [Link2](https://docs.google.com/document/d/1gIs0jYEh_8cdvvjg--KoDVMdUoURq-yv8D-_Xe3dd8M/edit)


Hope these can help!
